--- #YAML:1.0
name: Array-Unique
version: 0.06
author: Gabor Szabo <gabor@pti.co.il>
abstract: Tie-able array that allows only unique values
license: perl
requires:
  Test::More: 0.47
  perl: 0.006
provides:
  Array::Unique:
    file: lib/Array/Unique.pm
    version: 0.06
generated_by: Module::Build version 0.25_01
