--- #YAML:1.0
name: Array-Unique
version: 0.07
author:
  - Gabor Szabo <gabor@pti.co.il>
abstract: Tie-able array that allows only unique values
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
