# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Array-Unique
version:      0.04
version_from: Unique.pm
installdirs:  site
requires:
    Test::More:                    0.47
    Tie::IxHash:                   1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
